name: Call Private Repo Workflow

on: 
  workflow_dispatch: 

jobs:
  reusable_workflow_job:
    uses: ldraney/dotfiles-codespace/.github/workflows/private-workflow.yml@master
    secrets:
      envPAT: ${{ secrets.envPAT }}