name: Call Private Repo Workflow

on: 
  workflow_dispatch: 

jobs:
  reusable_workflow_job:
    uses: ldraney/private-repo/.github/workflows/pizza-workflow.yml@master
    secrets:
      envPAT: ${{ secrets.envPAT }}