name: Call Private Repo Workflow

on: 
  workflow_dispatch: 

jobs:
  trigger-private-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in private repo
        run: |
          curl -XPOST -H "Authorization: token ${{ secrets.envPAT }}" -H "Accept: application/vnd.github.v3+json" \
          -d '{"event_type": "trigger-private-workflow"}' \
          https://api.github.com/repos/ldraney/private-repo/dispatches      
