name: Call Private Repo Workflow

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (dev, staging, or perf)'
        required: true
        type: string
      ref:
        type: string
        description: branch or tag or hash
        required: true

jobs:
  trigger-private-workflow:
    runs-on: ubuntu-latest  # specify the runner
    name: first job
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}

    - name: Trigger Workflow
      uses: ./.github/actions/trigger-workflow-and-wait
      with:
        owner: ldraney
        repo: private-repo
        github_token: ${{ secrets.envPAT }}
        workflow_file_name: private-workflow.yml
        ref: master
        wait_interval: 1
        client_payload: '{"environment": "${{ github.event.inputs.environment }}"}'
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
