name: Call Private Repo Workflow

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (dev, staging, or perf)'
        required: true
        type: string
      ref:
        type: string
        description: branch or tag or hash
        required: true

jobs:
  trigger-private-workflow:
    runs-on: ubuntu-latest  # specify the runner
    # name: first job
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Trigger and Wait for Workflow
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.ENVPAT }}
        script: |
          const path = '.github/scripts/workflow-trigger-and-wait.js';
          const triggerAndWait = require(path);
          triggerAndWait({github, context});


    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: hello-world-output
        repo: ldraney/private-repo
        path: artifacts

    - name: Display Artifact Content
      run: cat artifacts/hello-world-output/output.txt
