name: Call Private Repo Workflow

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (dev, staging, or perf)'
        required: true
        type: string

jobs:
  trigger-private-workflow:
    runs-on: ubuntu-latest  # specify the runner
    name: first job
    steps:
    - name: Trigger Workflow
      uses: ./.github/actions/test-workflow-call-pvt.yml
      with:
        owner: ldraney
        repo: private-repo
        github_token: ${{ secrets.envPAT }}
        # github_user: github-user
        workflow_file_name: private-workflow.yml
        ref: master
        wait_interval: 1
        client_payload: '{"environment": "${{ github.event.inputs.environment }}"}'
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
