name: Call Private Repo Workflow

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (dev, staging, or perf)'
        required: true
        type: string

jobs:
  trigger-private-workflow:
    runs-on: ubuntu-latest  # specify the runner
    name: first job
    steps:
    - name: Trigger Workflow
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: department-of-veterans-affairs
        repo: vanotify-infra
        github_token: ${{ secrets.envPAT }}
        github_user: github-user
        workflow_file_name: private-workflow.yml
        ref: master
        wait_interval: 1
        client_payload: '{}'
        propagate_failure: true
        trigger_workflow: true
        wait_workflow: true
