name: Call Private Repo Workflow

on: 
  workflow_dispatch: 

jobs:
  call-workflow-passing-data:
    uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    secrets:
      envPAT: ${{ secrets.envPAT }}