name: Call Private Repo Workflow

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (dev, staging, or perf)'
        required: true
        type: string

jobs:
  trigger-private-workflow:
    name: first job
    uses: convictional/trigger-workflow-and-wait@v1.6.1
    with:
      owner: department-of-veterans-affairs/vanotify-infra
      repo: vanotify-infra
      github_token: ${{ secrets.envPAT }}
