name: Call Private Repo Workflow

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (dev, staging, or perf)'
        required: true
        type: string

jobs:
  trigger-private-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in private repo
        run: |
          curl -XPOST -H "Authorization: token ${{ secrets.envPAT }}" -H "Accept: application/vnd.github.v3+json" \
          -d '{"event_type": "trigger-private-workflow", "client_payload": {"environment": "${{ github.event.inputs.environment }}"}' \
          https://api.github.com/repos/ldraney/private-repo/dispatches

  trigger-private-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in private repo
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: ldraney
          repo: private-repo
          github_token: ${{ secrets.PRIVATE_REPO_GITHUB_TOKEN }}
          workflow_file_name: main.yml
          client_payload: '{"environment": "${{ github.event.inputs.environment }}"}'

